### PR TITLE
Enhance Style with Expanded Italics Scope for 'Italicsify for Operator Mono'

### PR DESCRIPTION
**Pull request by dylandifilippo**
## Proposed changes

I added some settings to extends the scope of "Italicsify for Operator Mono". In my opinion it makes the theme even better.

If the pull request addresses a specific issue or feature request, be sure to reference it here by linking to the relevant issue.

## Screenshots

Include screenshots to demonstrate the changes made by this pull request. This include before-and-after comparisons or specific examples of the modified functionality.

### Before

CleanShot 2024-04-30 at 11 29 53@2x

### After

CleanShot 2024-04-30 at 14 56 47@2x

## Checklist

Before submitting this pull request, ensure that you have completed the following tasks:<br>
(_Put an `x` in the boxes that apply._)

- [ x] I have read and understood the [CONTRIBUTING](https://github.com/wesbos/cobalt2-vscode/blob/master/.github/CONTRIBUTING.md) guidelines.
- [ x] I have performed a self-review of my code.
- [ x] I have added relevant screenshots or visual aids to showcase the changes made by this pull request.

### CODE REVIEW

**Comment by wesbos** [comment]
hmmm I tihnk this is a bit much, but it would be cool to have a setting to turn them on.

That, or add this to the docs on how to add this settings to your own settings.json file

**Comment by dylandifilippo** [comment]
Thanks for the reply.

I will remove those changes from the code and add a little guide to the doc. It will be the most convenient solution.

**Comment by dylandifilippo** [comment]
@wesbos Let me know if it is ok for you now 😊

**Comment by dylandifilippo** [comment]
@wesbos How can I add reviewers ?

**Comment by dylandifilippo** [comment]
I closed the PR since I cannot add a reviewer for several months

**Pull request closed without merging**
