### PR TITLE
Python `def` and `class` coloring fixes.

### LINKED ISSUE #109: class and def reserverd words are not colored diferently.
This make confuse to read, would be nice to have different colors for `def` and `class`

image

### PR DESCRIPTION
**Pull request by wsantos**
Fixes #109

### CODE REVIEW

**Comment by wsantos** [comment]
Here it's the results: 

image

**Comment by palashmon** [comment]
Hi, thanks for your contribution.

Just wanted to know if you have also tested this with a `*.py` file extension? If yes, could you please also add that sample file inside the `demo` folder for future reference purpose.

Regards!

**Comment by wesbos** [comment]
thank you - will cut a release shortly :) 

Thanks to both of you :D

**Comment by yujinyuz** [comment]
Hi @wsantos . I know this has been a year already but I'm still experiencing this one despite the fix applied.

Screen Shot 2019-10-15 at 10 10 29 PM


But I did find a workaround by adding this:

```json
"editor.tokenColorCustomizations": {
    "[Cobalt2]": {
        "textMateRules": [
            {
                "name": "Keyword",
                "scope": "keyword, storage.type.class",
                "settings": {
                    "foreground": "#ff9d00"
                }
            }
        ]
    }
},
```

Screen Shot 2019-10-15 at 10 01 42 PM


I was just wondering if there was still something that could fix this without doing the workaround I did. I've already tried uninstalling all of my extensions and reinstalled Cobalt2 Theme but I'm still getting the same output.

**Pull request merged**
