### PR TITLE
New statusbar debugging colors

### PR DESCRIPTION
**Pull request by carolitascl**

### CODE REVIEW

**Comment by carolitascl** [comment]
image

**Comment by carolitascl** [comment]
image

**Comment by palashmon** [comment]
Hi, could you please post how it used to look before the changes?
It would help to review the before & after effects. You can post just the lower part like:

**After:**

pr-108-updated

Regards!

**Comment by carolitascl** [comment]
**Before:**
image

**After**

image

**Comment by carolitascl** [comment]
**Statusbar Hover Before**

image

**Statusbar Hover After:**

image

**Comment by wesbos** [comment]
Thank you! this is great

**Comment by carolitascl** [comment]
:)

**Pull request merged**
