### PR TITLE
Fix Version control merge conflict highlighting Issue

### PR DESCRIPTION
**Pull request by ayodeleopetumo**
Hi Wes,

Took a shot at fixing the merge conflict highlighting issue raise by @noeladd

### CODE REVIEW

**Comment by wesbos** [comment]
@ayodeleopetumo  can you show me a screenshot of this?

**Comment by ayodeleopetumo** [comment]
Hi @wesbos the screenshot as requested 

screen shot 2018-04-06 at 3 42 53 pm

**Comment by wesbos** [comment]
thanks!

**Comment by wesbos** [comment]
will cut a relase soon

**Comment by lamartire** [comment]
:tada:

**Comment by umpox** [comment]
Thanks for this @ayodeleopetumo any news on the next release @wesbos ?

**Comment by JVPartanen** [comment]
@wesbos We still need this "merge conflict highlighting" fix to make Cobalt2 prefect!!
Thank you!

**Comment by ItamarShDev** [comment]
@wesbos any news about it?

**Comment by TomYeoman** [comment]
Looking forward to this, currently change my theme when resolving conflicts! 👍

**Comment by JVPartanen** [comment]
@hangai247 Awesome!!  I can finally continue using cobalt2 theme.

For VSCode Insiders edition the file to edit is:
`code ~/.vscode-insiders/extensions/wesbos.theme-cobalt2-2.1.6/theme/cobalt2.json`

**Pull request merged**
