### PR TITLE
Update CSS for dirty tab circle / cross

### PR DESCRIPTION
**Pull request by verpixelt**
This PR adjusts the selector and CSS properties for the dirty tab circle and cross (hover while in dirty state).
dirty-tab

### CODE REVIEW

**Comment by thedavefulton** [comment]
FWIW, the 'dirty tab circle' was still gray after installing the theme and following the instructions in the README. However, after updating the `cobalt2-custom-hacks.css` file with the exact changes proposed by @verpixelt the 'dirty tab circle' is behaving as expected. 🙌

**Comment by mdgeer** [comment]
Same for me. Made the changes @verpixelt suggested and dirty tab works as it's supposed to. :)

**Comment by wesbos** [comment]
thanks

**Comment by wesbos** [comment]
:) i meant to add a smiley!

**Pull request merged**
