### PR TITLE
Fixes sidebar highlight issue #37 

### PR DESCRIPTION
**Pull request by abdelrahmanrifai**
Fixes sidebar highlight issue #37 

cobalt2-sidebar

### CODE REVIEW

**Comment by wesbos** [comment]
thanks - what about the changing FFFFFF00 to null? Does that affect the colouring at all?

**Comment by abdelrahmanrifai** [comment]
I found many themes support sidebar highlighting. So when I deep dive into those themes files and VS Code [code](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/activitybar/activitybarActions.ts#L706) - I found that it's all related to Contrast Colors specifically the [contrastActiveBorder](https://github.com/Microsoft/vscode/blob/6c95d55f5768979c812404830ebdf6042b04f708/src/vs/platform/theme/common/colorRegistry.ts#L154).

Some themes developers set `contrastActiveBorder` to `null`, others drop it all together.

Maybe I was wrong about changing all `ffffff00` to `null` in this commit, I could just change `activityBar.foreground` to `#fff` and remove `contrastActiveBorder` `contrastBorder` and it will work just fine! **_Shall I do that in another commit?_**

**Comment by wesbos** [comment]
Yes please - it's nice to keep them separate so I can look back and see why it was set to null and not be mixed up in some sidebar styling. Thanks!

**Comment by abdelrahmanrifai** [comment]
Done! 🙌

Discovered another issue with find & replace highlighting 😅 
issue

**Comment by wesbos** [comment]
thanks!

**Pull request merged**
