### PR TITLE
feat: improve modified changes visibility on editor gutter

### PR DESCRIPTION
**Pull request by refl3ction**
### Description

It was really hard to see the changed lines on the gutter, this new color will make it much easier to see.

#### Before
image

#### After
image

### CODE REVIEW

**Comment by refl3ction** [comment]
@palashmon can you take a look at it?

**Review by palashmon — APPROVED** [review]
LGTM

**Comment by palashmon** [comment]
I will merge this once we get the approval from @wesbos in case we need some modifications to the color.

**Comment by wesbos** [comment]
Should be the standard yellow I think. #ffc600

**Comment by refl3ction** [comment]
Updated to standard yellow

**Pull request merged**
